// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace MyApp.Models;

public class Category
{
    [JsonPropertyName("id")]
    public int Id { get; set; }
    [JsonPropertyName("name")]
    public string Name { get; set; }
    [JsonPropertyName("parent")]
    public string? Parent { get; set; }
}
