// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
using System.Diagnostics.CodeAnalysis;

namespace GeneratedModels;

[ExcludeCodeCoverage]
[ExcludeCodeCoverage]
public class Customfields
{
    [JsonPropertyName("giftWrap")]
    public bool Giftwrap { get; set; }
    [JsonPropertyName("giftMessage")]
    public string Giftmessage { get; set; }
    [JsonPropertyName("internalPriority")]
    public int Internalpriority { get; set; }
}
