// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
using System.Diagnostics.CodeAnalysis;

namespace GeneratedModels;

[ExcludeCodeCoverage]
[ExcludeCodeCoverage]
public class Customer
{
    [JsonPropertyName("customerId")]
    public string Customerid { get; set; }
    [JsonPropertyName("firstName")]
    public string Firstname { get; set; }
    [JsonPropertyName("lastName")]
    public string Lastname { get; set; }
    [JsonPropertyName("email")]
    public string Email { get; set; }
    [JsonPropertyName("phone")]
    public string Phone { get; set; }
    [JsonPropertyName("loyaltyTier")]
    public string Loyaltytier { get; set; }
    [JsonPropertyName("shippingAddress")]
    public Shippingaddress Shippingaddress { get; set; }
    [JsonPropertyName("billingAddress")]
    public Shippingaddress Billingaddress { get; set; }
}
