// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
using System.Diagnostics.CodeAnalysis;

namespace GeneratedModels;

[ExcludeCodeCoverage]
[ExcludeCodeCoverage]
public class Deviceinfo
{
    [JsonPropertyName("type")]
    public string Type { get; set; }
    [JsonPropertyName("os")]
    public string Os { get; set; }
    [JsonPropertyName("browser")]
    public string Browser { get; set; }
    [JsonPropertyName("screenResolution")]
    public string Screenresolution { get; set; }
}
