// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
using System.Diagnostics.CodeAnalysis;

namespace GeneratedModels;

[ExcludeCodeCoverage]
[ExcludeCodeCoverage]
public class Installments
{
    [JsonPropertyName("enabled")]
    public bool Enabled { get; set; }
    [JsonPropertyName("numberOfPayments")]
    public int Numberofpayments { get; set; }
    [JsonPropertyName("paymentSchedule")]
    public List<object> Paymentschedule { get; set; }
}
