// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
using System.Diagnostics.CodeAnalysis;

namespace GeneratedModels;

[ExcludeCodeCoverage]
[ExcludeCodeCoverage]
public class Lineitem
{
    [JsonPropertyName("lineItemId")]
    public string Lineitemid { get; set; }
    [JsonPropertyName("product")]
    public Product Product { get; set; }
    [JsonPropertyName("quantity")]
    public int Quantity { get; set; }
    [JsonPropertyName("discountPercent")]
    public double Discountpercent { get; set; }
    [JsonPropertyName("lineTotal")]
    public double Linetotal { get; set; }
}
