// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
using System.Diagnostics.CodeAnalysis;

namespace GeneratedModels;

[ExcludeCodeCoverage]
[ExcludeCodeCoverage]
public class Metadata
{
    [JsonPropertyName("source")]
    public string Source { get; set; }
    [JsonPropertyName("campaign")]
    public string Campaign { get; set; }
    [JsonPropertyName("referrer")]
    public string Referrer { get; set; }
    [JsonPropertyName("deviceInfo")]
    public Deviceinfo Deviceinfo { get; set; }
    [JsonPropertyName("customFields")]
    public Customfields Customfields { get; set; }
}
