// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
using System.Diagnostics.CodeAnalysis;

namespace GeneratedModels;

[ExcludeCodeCoverage]
[ExcludeCodeCoverage]
public class Payment
{
    [JsonPropertyName("method")]
    public string Method { get; set; }
    [JsonPropertyName("transactionId")]
    public string Transactionid { get; set; }
    [JsonPropertyName("amountCharged")]
    public double Amountcharged { get; set; }
    [JsonPropertyName("currency")]
    public string Currency { get; set; }
    [JsonPropertyName("cardLastFour")]
    public string Cardlastfour { get; set; }
    [JsonPropertyName("installments")]
    public Installments Installments { get; set; }
}
