// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
using System.Diagnostics.CodeAnalysis;

namespace GeneratedModels;

[ExcludeCodeCoverage]
[ExcludeCodeCoverage]
public class Product
{
    [JsonPropertyName("sku")]
    public string Sku { get; set; }
    [JsonPropertyName("name")]
    public string Name { get; set; }
    [JsonPropertyName("category")]
    public string Category { get; set; }
    [JsonPropertyName("unitPrice")]
    public double Unitprice { get; set; }
    [JsonPropertyName("tags")]
    public List<string> Tags { get; set; }
}
