// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;
using System.Diagnostics.CodeAnalysis;

namespace GeneratedModels;

[ExcludeCodeCoverage]
[ExcludeCodeCoverage]
public class Root
{
    [JsonPropertyName("id")]
    public string Id { get; set; }
    [JsonPropertyName("orderDate")]
    public string Orderdate { get; set; }
    [JsonPropertyName("status")]
    public string Status { get; set; }
    [JsonPropertyName("totalAmount")]
    public double Totalamount { get; set; }
    [JsonPropertyName("isPriority")]
    public bool Ispriority { get; set; }
    [JsonPropertyName("notes")]
    public string? Notes { get; set; }
    [JsonPropertyName("customer")]
    public Customer Customer { get; set; }
    [JsonPropertyName("lineItems")]
    public List<Lineitem> Lineitems { get; set; }
    [JsonPropertyName("payment")]
    public Payment Payment { get; set; }
    [JsonPropertyName("metadata")]
    public Metadata Metadata { get; set; }
    [JsonPropertyName("tags")]
    public List<string> Tags { get; set; }
    [JsonPropertyName("createdAt")]
    public string Createdat { get; set; }
    [JsonPropertyName("updatedAt")]
    public string Updatedat { get; set; }
}
