// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace MyApp.Models;

public class Contact
{
    [JsonPropertyName("email")]
    public string Email { get; set; }
    [JsonPropertyName("phone")]
    public string Phone { get; set; }
}
