// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace MyApp.Models;

public class Root
{
    [JsonPropertyName("id")]
    public int Id { get; set; }
    [JsonPropertyName("name")]
    public string Name { get; set; }
    [JsonPropertyName("price")]
    public double Price { get; set; }
    [JsonPropertyName("tags")]
    public List<string> Tags { get; set; }
    [JsonPropertyName("category")]
    public Category Category { get; set; }
    [JsonPropertyName("supplier")]
    public Supplier Supplier { get; set; }
}
