// <auto-generated />
#nullable enable
using System.Text.Json.Serialization;

namespace MyApp.Models;

public class Supplier
{
    [JsonPropertyName("id")]
    public int Id { get; set; }
    [JsonPropertyName("company_name")]
    public string CompanyName { get; set; }
    [JsonPropertyName("contact")]
    public Contact Contact { get; set; }
}
