using System.Text;
using JsonToCSharp.App.Models;

namespace JsonToCSharp.App;

public static class FileWriter
{
    public static void WriteClasses(List<ClassDefinition> classes, string outputDir, string namespaceName)
    {
        Directory.CreateDirectory(outputDir);

        foreach (var classDef in classes)
        {
            var filePath = Path.Combine(outputDir, $"{classDef.ClassName}.cs");
            var content = GenerateFileContent(classDef, namespaceName);
            File.WriteAllText(filePath, content);
        }
    }

    private static string GenerateFileContent(ClassDefinition classDef, string namespaceName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine("using System.Diagnostics.CodeAnalysis;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine("[ExcludeFromCodeCoverage]");
        sb.Append(CSharpGenerator.GenerateClass(classDef));
        sb.AppendLine();
        return sb.ToString();
    }
}
